### ISSUE TITLE
dashSlicer.NEWSlicer

### ISSUE THREAD

**Issue by jackxieweiwu** [panda-media/rtmpmate#1]
dashSlicer.NEWSlicer(1000, 8000, 5, 1000, this)

//videoTimescale and audioTimescale for input
func NEWSlicer(fps, videoTimescale,audioTimescale, minLengthMS, maxLengthMS, maxSegmentCountInMPD int, receiver FMP4Receiver) (slicer *DASHSlicer, err error) {
	slicer = &DASHSlicer{}

	if maxSegmentCountInMPD < 2 || nil == receiver {
		err = errors.New("invalid param ")
		return nil, err
	}
	if minLengthMS < 1000 {
		minLengthMS = 1000
	}
	if maxLengthMS < minLengthMS {
		maxLengthMS = minLengthMS
	}
	if videoTimescale <= 60 {
		videoTimescale = 90000
	}

	slicer.minSegmentDuration = minLengthMS
	slicer.maxSegmentDuration = maxLengthMS
	slicer.maxSegmentCountInMPD = maxSegmentCountInMPD
	slicer.receiver = receiver
	slicer.videoTimescale = videoTimescale
	slicer.audioTimescale=audioTimescale

	slicer.h264Transfer.Init(fps)
	slicer.init()

	return
}

what?

**Comment by oddengine** [comment]
The DASHMuxer in this project is broken now, while the interfaces of muxer-fmp4 has been changed, so is the FMP4Muxer. And I'm planning to write a built-in muxer after the National Day.
