### ISSUE TITLE
Webhook on_publish to URL possible?

### ISSUE THREAD

**Issue by Tortschi** [panda-media/rtmpmate#2]
Hello,

is it possible to send a request via on_publish/on_publish_done to http URL?

Thanks for answer

**Comment by oddengine** [comment]
Yes, predefine a upstream server, which shall be linked in by the name, and set enable to true.

**Comment by Tortschi** [comment]
Can you show me an Config Example with an External IP Adress?

**Comment by oddengine** [comment]
Please download the latest static build, and have a look at conf/mated.conf.
1. Define a upstream server inside any protocol phase. For example:
"http": {
	"upstream": [{
		**"name":     "web",**
		"address":  "192.168.2.51",
		"port":         80,
		"flag":         "normal",
		"weight":     5,
		"timeout":   5,
		"max_fails": 0
	}],
...

2. Specify upstream name, and enable the events.
"on_publish": {
	"protocol": "http://",
	"method":   "GET",
	**"upstream": "web",**
	"path":     "/uis/rcsss/addOrMod/executeLive",
	"args":     "",
	**"enable":    true**
},

**Comment by oddengine** [comment]
It will send a GET request to http://192.168.2.51/uis/rcsss/addOrMod/executeLive. If you defined several IP address with the same name, it will send to only one address a time. Known as load balance.
