### ISSUE TITLE
Start.sh not started

### ISSUE THREAD

**Issue by Tortschi** [panda-media/rtmpmate#3]
Hello,

i download the Linux compiled ZIP File and start the start.sh Script but it dont work. I look into Background Processes but it dont run. I change Rights of (start.sh), (stop.sh) and mated with chmod +x .

Can you help me to test your Tool?

Thanks

**Comment by oddengine** [comment]
What does the log say? Have you picked  an  **unused** CDKey from the readme file?

**Comment by Tortschi** [comment]
I think it not start. It not create any Log File. I use a correct CDKey from Readme. What else could be the problem?

**Comment by oddengine** [comment]
Then don't use the script tool. Open a Terminal in the folder, and run it directly:
# ./bin/mated

There should be a folder being created named logs, if it ran successfully.

By the way, what system and platform are you using? I have only tested on CentOS7.

**Comment by Tortschi** [comment]
Hello @studease,

i get this Error: root@ip-172-31-36-216:~/rtmp/bin# ./mated
bash: ./mated: No such file or directory

Hope you can help me.

**Comment by oddengine** [comment]
Does the file named mated do exist? Or it’s the rights not allowed. Try:
# chmod -R 777 /bin
Or run it by:
# su ./bin/mated

Note: Don’t step into the bin folder.

**Comment by Tortschi** [comment]
Hello,

i think its a Problem on ubuntu 16.04 it only works for Centos. I get this Error:
`unable to execute ./bin/mated: No such file or directory`

**Comment by oddengine** [comment]
I’ll build more statics in few days.

**Comment by Tortschi** [comment]
Ok is it possible to know the day and on what system you will build the new statics?

thanks

**Comment by oddengine** [comment]
One or two days more. I’ll build it on MacOS and Debian. If it cannot run on Ubuntu, a new build will also be made.

**Comment by oddengine** [comment]
Hi Tortschi,
A new build on Debian is available. It can run on Ubantu 16, too.

**Comment by Tortschi** [comment]
Ok i test it today and give you Feedback.
